language: go
go:
  - 1.9

jdk:
  - oraclejdk9

sudo: false

branches:
  only:
    - master

before_install:
  - wget http://archive.apache.org/dist/zookeeper/zookeeper-${zk_version}/zookeeper-${zk_version}.tar.gz
  - tar -zxvf zookeeper*tar.gz && zip -d zookeeper-${zk_version}/contrib/fatjar/zookeeper-${zk_version}-fatjar.jar 'META-INF/*.SF' 'META-INF/*.DSA'
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - jdk_switcher use oraclejdk9
  - go build ./...
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...
  - go test -race -covermode atomic -coverprofile=profile.cov ./zk
    #  - goveralls -coverprofile=profile.cov -service=travis-ci

env:
  matrix:
    - zk_version=3.4.10
